name: Deploy to AWS dev

on:
  workflow_dispatch: {}
  push:
    branches:
      - dev 

jobs:
  Build:
    runs-on: ubuntu-latest # ["self-hosted", "dev"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build Docker image
        run: docker build --no-cache -t myapp:${{ github. run_number }} .

      - name: List Docker images
        run: docker images
      
      - name: Log in to Docker Hub (if needed)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Tag Docker Image
        run: docker tag myapp:${{ github. run_number }} ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github. run_number }}

      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github. run_number }}

  Deploy:
    needs: Build
    runs-on: ["self-hosted", "dev"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull Image from docker hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github. run_number }}

      - name: Stop and remove old container (if exists)
        run: |
          docker stop myapp || true
          docker rm myapp || true

      - name: Remove old images
        run: |
          docker rmi -f ${{ secrets.DOCKER_USERNAME }}/myapp

      - name: Run Docker container
        run: |
          docker run -d --name myapp -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github. run_number }}
